# Generate Ds(Rpop, Rsm) coefficient table
# Load fitted models
pacman::p_load(ggplot2,
               here,
               magrittr,
               dplyr,
               tidyr,
               texreg)
project_dir <- here::here()
RpopRsm_mod <- readRDS(file = paste0(project_dir, "/Data", "/RpopRsm_model.RDS"))
RpopRsm_mod_poly <- readRDS(file = paste0(project_dir, "/Data", "/RpopRsm_model_poly.RDS"))

coef_names <- list(
  "(Intercept)" = "Constant",
  "subjects_per_item" = "Subjects/Item",
  "items_per_factor" = "Items/Factor",
  "factors" = "Factors",
  "factor_loading" = "Factor Loading",
  "model_error" = "Model Error",
  "smoothing_methodAPA" = "Smoothing Method (APA)",
  "smoothing_methodBY" = "Smoothing Method (BY)",
  "smoothing_methodKB" = "Smoothing Method (KB)",
  "I(subjects_per_item^2)" = "Subjects/Item$^2$",
  "I(factor_loading^2)" = "Factor Loading$^2$",
  "I(factors^2)" = "Factors$^2$",
  "I(model_error^2)" = "Model Error$^2$",
  "subjects_per_item:items_per_factor" = "Subjects/Item $\\times$ Items/Factor",
  "subjects_per_item:factors" = "Subjects/Item $\\times$ Factors",
  "subjects_per_item:factor_loading" = "Subjects/Item $\\times$ Factor Loading",
  "subjects_per_item:model_error" = "Subjects/Item $\\times$ Model Error",
  "subjects_per_item:smoothing_methodAPA" = "Subjects/Item $\\times$ Smoothing Method (APA)",
  "subjects_per_item:smoothing_methodBY" = "Subjects/Item $\\times$ Smoothing Method (BY)",
  "subjects_per_item:smoothing_methodKB" = "Subjects/Item $\\times$ Smoothing Method (KB)",
  "subjects_per_item:I(factor_loading^2)" = "Subjects/Item $\\times$ Factor Loading$^2$",
  "subjects_per_item:I(factors^2)" = "Subjects/Item $\\times$ Factors$^2$",
  "subjects_per_item:I(model_error^2)" = "Subjects/Item $\\times$ Model Error$^2$",
  "items_per_factor:factors" = "Items/Factor $\\times$ Factors",
  "items_per_factor:factor_loading" = "Items/Factor $\\times$ Factor Loading",
  "items_per_factor:model_error" = "Items/Factor $\\times$ Model Error",
  "items_per_factor:smoothing_methodAPA" = "Items/Factor $\\times$ Smoothing Method (APA)",
  "items_per_factor:smoothing_methodBY" = "Items/Factor $\\times$ Smoothing Method (BY)",
  "items_per_factor:smoothing_methodKB" = "Items/Factor $\\times$ Smoothing Method (KB)",
  "items_per_factor:I(subjects_per_item^2)" = "Items/Factor $\\times$ Subjects/Item$^2$",
  "items_per_factor:I(factor_loading^2)" = "Items/Factor $\\times$ Factor Loading$^2$",
  "items_per_factor:I(factors^2)" = "Items/Factor $\\times$ Factors$^2$",
  "items_per_factor:I(model_error^2)" = "Items/Factor $\\times$ Model Error$^2$",
  "factors:factor_loading" = "Factors $\\times$ Factor Loading",
  "factors:model_error" = "Factors $\\times$ Model Error",
  "factors:smoothing_methodAPA" = "Factors $\\times$ Smoothing Method (APA)",
  "factors:smoothing_methodBY" = "Factors $\\times$ Smoothing Method (BY)",
  "factors:smoothing_methodKB" = "Factors $\\times$ Smoothing Method (KB)",
  "factors:I(subjects_per_item^2)" = "Factors $\\times$ Subjects/Item$^2$",
  "factors:I(factor_loading^2)" = "Factors $\\times$ Factor Loading$^2$",
  "factors:I(factors^2)" = "Factors $\\times$ Factors$^2$",
  "factors:I(model_error^2)" = "Factors $\\times$ Model Error$^2$",
  "factor_loading:model_error" = "Factor Loading $\\times$ Model Error",
  "factor_loading:smoothing_methodAPA" = "Factor Loading $\\times$ Smoothing Method (APA)",
  "factor_loading:smoothing_methodBY" = "Factor Loading $\\times$ Smoothing Method (BY)",
  "factor_loading:smoothing_methodKB" = "Factor Loading $\\times$ Smoothing Method (KB)",
  "factor_loading:I(subjects_per_item^2)" = "Factor Loading $\\times$ Subjects/Item$^2$",
  "factor_loading:I(factors^2)" = "Factor Loading $\\times$ Factors$^2$",
  "factor_loading:I(model_error^2)" = "Factor Loading $\\times$ Model Error$^2$",
  "model_error:smoothing_methodAPA" = "Model Error $\\times$ Smoothing Method (APA)",
  "model_error:smoothing_methodBY" = "Model Error $\\times$ Smoothing Method (BY)",
  "model_error:smoothing_methodKB" = "Model Error $\\times$ Smoothing Method (KB)",
  "model_error:I(subjects_per_item^2)" = "Model Error $\\times$ Subjects/Item$^2$",
  "model_error:I(factor_loading^2)" = "Model Error $\\times$ Factor Loading$^2$",
  "model_error:I(factors^2)" = "Model Error $\\times$ Factors$^2$",
  "smoothing_methodAPA:I(subjects_per_item^2)" = "Smoothing Method (APA) $\\times$ Subjects/Item$^2$",
  "smoothing_methodBY:I(subjects_per_item^2)" = "Smoothing Method (BY) $\\times$ Subjects/Item$^2$",
  "smoothing_methodKB:I(subjects_per_item^2)" = "Smoothing Method (KB) $\\times$ Subjects/Item$^2$",
  "smoothing_methodAPA:I(factor_loading^2)" = "Smoothing Method (APA) $\\times$ Factor Loading$^2$",
  "smoothing_methodBY:I(factor_loading^2)" = "Smoothing Method (BY) $\\times$ Factor Loading$^2$",
  "smoothing_methodKB:I(factor_loading^2)" = "Smoothing Method (KB) $\\times$ Factor Loading$^2$",
  "smoothing_methodAPA:I(factors^2)" = "Smoothing Method (APA) $\\times$ Factors$^2$",
  "smoothing_methodBY:I(factors^2)" = "Smoothing Method (BY) $\\times$ Factors$^2$",
  "smoothing_methodKB:I(factors^2)" = "Smoothing Method (KB) $\\times$ Factors$^2$",
  "smoothing_methodAPA:I(model_error^2)" = "Smoothing Method (APA) $\\times$ Model Error$^2$",
  "smoothing_methodBY:I(model_error^2)" = "Smoothing Method (BY) $\\times$ Model Error$^2$",
  "smoothing_methodKB:I(model_error^2)" = "Smoothing Method (KB) $\\times$ Model Error$^2$",
  "I(subjects_per_item^2):I(factor_loading^2)" = "Subjects/Item$^2$ $\\times$ Factor Loading$^2$",
  "I(subjects_per_item^2):I(factors^2)" = "Subjects/Item$^2$ $\\times$ Factors$^2$",
  "I(subjects_per_item^2):I(model_error^2)" = "Subjects/Item$^2$ $\\times$ Model Error$^2$",
  "I(factor_loading^2):I(factors^2)" = "Factor Loading$^2$ $\\times$ Factors$^2$",
  "I(factor_loading^2):I(model_error^2)" = "Factor Loading$^2$ $\\times$ Model Error$^2$",
  "I(factors^2):I(model_error^2)" = "Factors$^2$ $\\times$ Model Error$^2$"
)

RpopRsm_coef_tab <- texreg::texreg(
  l = list(RpopRsm_mod,
           RpopRsm_mod_poly),
  custom.coef.map = coef_names,
  custom.model.names = c("Linear Model", "Polynomial Model"),
  custom.note = "",
  digits = 3,
  stars = 0,
  dcolumn = TRUE,
  longtable = TRUE,
  use.packages = FALSE,
  single.row = TRUE,
  caption.above = TRUE,
  caption = "Coefficient estimates and standard errors for the linear and polynomial mixed effects models using $\\log[\\mathrm{D}_{\\mathrm{s}}(\\Rsm, \\Rpop)]$ as the dependent variable and estimating a random intercept for each indefinite correlation matrix.",
  label = "tab:distance-mod-summary")

# Right-align coefficient columns
# RpopRsm_coef_tab <- stringr::str_replace(RpopRsm_coef_tab, 
#                                          pattern = "\\{l c \\}", 
#                                          replacement = "\\{l r \\}")

writeLines(RpopRsm_coef_tab, 
           paste0(project_dir, "/Text", "/tabs", "/RpopRsm_coef_tab.txt"))
